### ISSUE TITLE
Enable OAuth 2.0 Token Introspection Endpoint

### ISSUE THREAD

**Issue by cgmv** [zalando/planb-tokeninfo#74] opened 2017-03-03 14:34 UTC
## User Story

**As:** Engineer 
**I want to:** learn about the content and metadata of a token. 
**So that:** I can transparently request information about the token

## Acceptance Criteria
- [ ] Introspect endpoint created
- [ ] `access_tokens` are validated using the signature
- [ ] the `active` boolean represents if a token is still good to be used or did it expire already. At no time should the response be altered as done currently in tokeninfo indicating that the token is invalid. That is semantically wrong.
- [ ] if the `token_type_hint` is omitted it must try to validate an `access_token` (default)
- [ ] Endpoint validates both access and refresh tokens

#### Rational

As far as the OAuth 2.0 [RFC6749] specification is concerned tokens are opaque.
Meaning that clients don't need to know anything about the content or structure of the token itself. That being said in our environment tokens contain a lot of metadata consumed by the receiving service. Therefore tokeninfo was introduced very early on to allow for a way to inspect the contents of a token in case you don't want to opt for Policy Decision Point to validate requests. But we don't have such thing. The way clients operate at the moment is to send the token to the tokeninfo endpoint and process the answer once receiving the token. 

#### Example Introspect

**Access Token Introspect**

``` HTTP
POST /oauth2/introspect HTTP/1.1
Host: zalando.com
Accept: application/json
Content-Type: application/x-www-form-urlencoded

token=eyJqls...== &token_type_hint=access_token
```

``` json
{
  "active": "true|false"
  "iss": "https://zalando.com",
  "aud": "ztoken",
  "sub": "3ccc20cb-ddfc-433f-9703-053a253aecf7",
  "azp": "ztoken",
  "tenant": "810d1d00-4312-43e5-bd31-d8373fdd24c7",
  "auth_time": 1485354373,  
  "exp": 1487946319,
  "iat": 1487942719,
}
```

**Refresh Token Introspect**

``` HTTP
POST /oauth2/introspect HTTP/1.1
Host: identity.zalando.com
Accept: application/json
Content-Type: application/x-www-form-urlencoded

token=9557d3b0r3889510&token_type_hint=refresh_token
```

``` HTTP
{ 
  "active": "true|false",
  "iss": "https://zalando.com",
  "aud": "$client_id",
  "sub": "$owner_uuid",
  "exp": 1487946319,
  "iat": 1487942719,
  "tenant": "810d1d00-4312-43e5-bd31-d8373fdd24c7"
}
```

## Links
- https://tools.ietf.org/html/rfc7662

**Comment by hjacobs** [comment] 2017-03-03 14:42
Duplicate of #32

**Comment by vroldanbet** [comment] 2017-03-28 10:14
Closing as duplicate

**Closed by vroldanbet** 2017-03-28 10:14 UTC
